services:
  - type: web
    name: shraddhabackend
    env: node
    rootDirectory: ShraddhaBackend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
