services:
  - type: web
    name: shraddha-backend
    env: node
    region: singapore
    rootDir: Intellisys/ShraddhaBackend
    buildCommand: "npm install"
    startCommand: "npm start"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        sync: false   # <-- secure, set in Render dashboard
